[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs", "setuptools_scm<6.0.0"]

[project]
classifiers = [
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Environment :: Web Environment",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Topic :: Documentation",
        "Topic :: Utilities",
        "Framework :: Sphinx :: Extension",
        "Framework :: Sphinx :: Domain",
]
dependencies = [
    "Sphinx>=4.0.0",
    "tree-sitter-matlab>=1.0.2",
    "tree-sitter>=0.21.3,<0.23.0",
]
description = 'Sphinx "matlabdomain" extension'
# Version from setuptools_scm
dynamic = ["version"]
license = "BSD"
license-files = ["LICENSE"]
maintainers = [{name = "JÃ¸rgen Cederberg", email = "jorgen@cederberg.be"}]
name = "sphinxcontrib-matlabdomain"
readme = "README.rst"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pre-commit",
    "defusedxml>=0.7.1",
    "sphinxcontrib-napoleon",
    ]
doc = [
    "sphinx_rtd_theme",
    "sphinxcontrib-napoleon",
]

[project.urls]
Homepage = "https://github.com/sphinx-contrib/matlabdomain"
Documentation = "https://sphinxcontrib-matlabdomain.readthedocs.io"
Download = "http://pypi.python.org/pypi/sphinxcontrib-matlabdomain"

[tool.hatch.build.hooks.vcs]
version-file = "sphinxcontrib/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["sphinxcontrib"]

[tool.hatch.version]
source = "vcs"

[tool.pytest.ini_options]
addopts = "--show-capture=all"
